name: secretariat_app
description: "A Flutter application for school secretariat and document archiving system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # مكتبات إدارة الملفات والإكسل
  excel: ^4.0.6
  path_provider: ^2.1.3
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  
  # مكتبات المسح الضوئي والتعرف على المستندات والـ QR
  mobile_scanner: ^5.2.3
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_barcode_scanning: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
